### ISSUE TITLE
AttributeError: 'UNetModel' object has no attribute 'enable_gradient_checkpointing'. Did you mean: '_return_value'?

### ISSUE THREAD

**Issue by threewood1** [mk-minchul/dcface#21]
Thank you for your work, I got something wrong during training. Here is the original error：

AttributeError: 'UNetModel' object has no attribute 'enable_gradient_checkpointing'. Did you mean: '_return_value'?

Did anyone meet this error? I got this error when I try to train the generator, and had try to solve it, but failed.

**Comment by threewood1** [comment]
/home/zrway/anaconda3/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
tmp directory : /home/zrway/project/xs/dcface_master/dcface-master/experiments/test-2023-10-12_10-36-59
removing tmp directory : /home/zrway/project/xs/dcface_master/dcface-master/experiments/test-2023-10-12_10-36-59
Current working directory : /home/zrway/project/xs/dcface_master/dcface-master/dcface/src
Saving Directory          : /home/zrway/project/xs/dcface_master/dcface-master/experiments/dcface/test_10-12_0
available_gpus------------ 2
Per GPU batchsize: 256
Global seed set to 123
Instantiating datamodule <src.datamodules.face_datamodule.FaceDataModule>
Instantiating model <src.trainer.Trainer>
loading model from /home/zrway/project/xs/dcface_master/dcface-master/dcface/pretrained_models/ffhq_10m.pt
UNetModel has 93.56 M params.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/zrway/project/xs/dcface_master/dcface-master/dcface/src/train.py", line 151, in <module>
    main()
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/zrway/project/xs/dcface_master/dcface-master/dcface/src/train.py", line 146, in main
    metric_dict, _ = train(cfg)
  File "/home/zrway/project/xs/dcface_master/dcface-master/dcface/src/train.py", line 56, in train
    model: LightningModule = hydra.utils.instantiate(cfg.trainer)()
  File "/home/zrway/project/xs/dcface_master/dcface-master/dcface/src/trainer.py", line 37, in __init__
    self.model.enable_gradient_checkpointing()
  File "/home/zrway/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNetModel' object has no attribute 'enable_gradient_checkpointing'. Did you mean: '_return_value'?

**Comment by threewood1** [comment]
I sovled this problem by using correct version of hydra
